# 개발 환경 설정

[server]
host = "127.0.0.1"
port = 8080
workers = 2

[logging]
level = "debug"

[cors]
enabled = true
allowed_origins = ["http://localhost:3000", "http://localhost:8080", "http://127.0.0.1:3000", "http://127.0.0.1:8080"]
