version: '3.8'

services:
  basic-pacs-server:
    build: .
    ports:
      - "8080:8080"
    environment:
      - RUN_MODE=development
      - HOST=0.0.0.0
      - PORT=8080
      - WORKERS=2
      - LOG_LEVEL=info
      - RUST_LOG=info
      - CORS_ENABLED=true
      - CORS_ORIGINS=*
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes:
      - ./config:/app/config:ro
