version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: pacs-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: pacs_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d pacs_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
