# Default configuration for Health Check Server
# These values can be overridden by:
# 1. config/{environment}.toml
# 2. .env file
# 3. Environment variables with APP_ prefix (highest priority)

[server]
host = "0.0.0.0"
port = 8080
workers = 4

[logging]
level = "info"
format = "json"

[cors]
enabled = true
allowed_origins = ["http://localhost:3000", "http://localhost:8080"]
allowed_methods = ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
allowed_headers = ["Content-Type", "Authorization", "X-Requested-With"]
expose_headers = ["Content-Length"]
max_age = 3600

[health_check]
enabled = true
endpoint = "/health"
response_format = "json"
