# Development configuration for Health Check Server
# This file overrides default.toml for development environment

[server]
host = "127.0.0.1"
port = 3000
workers = 2

[logging]
level = "debug"
format = "pretty"

[cors]
enabled = true
allowed_origins = [
    "http://localhost:3000", 
    "http://localhost:8080", 
    "http://127.0.0.1:3000",
    "http://127.0.0.1:8080"
]
allowed_methods = ["GET", "POST", "PUT", "DELETE", "OPTIONS", "PATCH"]
allowed_headers = [
    "Content-Type", 
    "Authorization", 
    "X-Requested-With",
    "Accept",
    "Origin"
]
expose_headers = ["Content-Length", "X-Total-Count"]
max_age = 3600

[health_check]
enabled = true
endpoint = "/health"
response_format = "json"
