# Production configuration for Health Check Server
# This file overrides default.toml for production environment

[server]
host = "0.0.0.0"
port = 8080
workers = 8

[logging]
level = "warn"
format = "json"

[cors]
enabled = false
allowed_origins = []
allowed_methods = ["GET"]
allowed_headers = ["Content-Type"]
expose_headers = []
max_age = 3600

[health_check]
enabled = true
endpoint = "/health"
response_format = "json"
