version: '3.8'

services:
  health-check-server:
    build: .
    ports:
      - "8080:8080"
    environment:
      - RUN_MODE=production
      - HOST=0.0.0.0
      - PORT=8080
      - LOG_LEVEL=info
      - CORS_ENABLED=true
    volumes:
      - ./config:/app/config:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # 개발 환경용
  health-check-server-dev:
    build: .
    ports:
      - "3000:3000"
    environment:
      - RUN_MODE=development
      - HOST=0.0.0.0
      - PORT=3000
      - LOG_LEVEL=debug
      - CORS_ENABLED=true
    volumes:
      - ./config:/app/config:ro
      - ./src:/app/src:ro
    restart: unless-stopped
    profiles:
      - dev

  # 테스트 환경용
  health-check-server-test:
    build: .
    ports:
      - "8081:8080"
    environment:
      - RUN_MODE=test
      - HOST=0.0.0.0
      - PORT=8080
      - LOG_LEVEL=debug
      - CORS_ENABLED=true
    volumes:
      - ./config:/app/config:ro
    restart: "no"
    profiles:
      - test
