import { TestSection } from './types';

export const getAnnotationSections = (): TestSection[] => [
  {
    title: '🏷️ Annotation Label 기능',
    description: 'Annotation Label 생성, 수정, 조회 테스트 (순차 실행)',
    isSequential: true,
    tests: [
      {
        name: '1️⃣ Label 없이 Annotation 생성',
        status: 'pending',
        isSequential: true,
        indentLevel: 0,
      },
      {
        name: '2️⃣ Label과 함께 Annotation 생성 (Tumor)',
        status: 'pending',
        dependencies: ['1️⃣ Label 없이 Annotation 생성'],
        indentLevel: 0,
      },
      {
        name: '3️⃣ 생성된 Annotation 조회 (Label 확인)',
        status: 'pending',
        dependencies: ['2️⃣ Label과 함께 Annotation 생성 (Tumor)'],
        indentLevel: 1,
      },
      {
        name: '4️⃣ Label 수정 (Tumor → Lesion)',
        status: 'pending',
        dependencies: ['3️⃣ 생성된 Annotation 조회 (Label 확인)'],
        indentLevel: 1,
      },
      {
        name: '5️⃣ 수정된 Label 확인',
        status: 'pending',
        dependencies: ['4️⃣ Label 수정 (Tumor → Lesion)'],
        indentLevel: 2,
      },
      {
        name: '6️⃣ 다양한 Label로 Annotation 생성 (Normal, Abnormal, Suspicious)',
        status: 'pending',
        dependencies: ['5️⃣ 수정된 Label 확인'],
        indentLevel: 0,
      },
      {
        name: '7️⃣ 모든 Annotation 조회 (Label 포함)',
        status: 'pending',
        dependencies: ['6️⃣ 다양한 Label로 Annotation 생성 (Normal, Abnormal, Suspicious)'],
        indentLevel: 1,
      },
      {
        name: '8️⃣ Label 빈 문자열로 수정',
        status: 'pending',
        dependencies: ['7️⃣ 모든 Annotation 조회 (Label 포함)'],
        indentLevel: 1,
      },
      {
        name: '9️⃣ 정리 (생성된 Annotation 삭제)',
        status: 'pending',
        dependencies: ['8️⃣ Label 빈 문자열로 수정'],
        indentLevel: 0,
        cleanup: true,
      },
    ],
  },
  {
    title: '🔐 Annotation 권한 관리',
    description: 'Annotation 생성/수정/삭제 권한 제어 및 권한 조회 API 테스트 (순차 실행)',
    isSequential: true,
    tests: [
      {
        name: '0️⃣ 사전 정리 (기존 테스트 프로젝트 삭제)',
        status: 'pending',
        isSequential: true,
        indentLevel: 0,
        cleanup: true,
      },
      {
        name: '1️⃣ 테스트용 프로젝트 생성',
        status: 'pending',
        isSequential: true,
        dependencies: ['0️⃣ 사전 정리 (기존 테스트 프로젝트 삭제)'],
        indentLevel: 0,
        delayAfter: 1000,
      },
      {
        name: '2️⃣ 사용자를 프로젝트 멤버로 추가',
        status: 'pending',
        dependencies: ['1️⃣ 테스트용 프로젝트 생성'],
        indentLevel: 1,
      },
      {
        name: '3️⃣ 개발 모드: 쿼리 파라미터로 Annotation 생성',
        status: 'pending',
        dependencies: ['2️⃣ 사용자를 프로젝트 멤버로 추가'],
        indentLevel: 1,
      },
      {
        name: '4️⃣ 개발 모드: 헤더로 Annotation 생성',
        status: 'pending',
        dependencies: ['3️⃣ 개발 모드: 쿼리 파라미터로 Annotation 생성'],
        indentLevel: 1,
      },
      {
        name: '5️⃣ 권한 조회 API 테스트',
        status: 'pending',
        dependencies: ['4️⃣ 개발 모드: 헤더로 Annotation 생성'],
        indentLevel: 1,
      },
      {
        name: '6️⃣ 소유자 Annotation 조회 테스트',
        status: 'pending',
        dependencies: ['5️⃣ 권한 조회 API 테스트'],
        indentLevel: 1,
      },
      {
        name: '7️⃣ READ_ALL 권한으로 다른 사용자 Annotation 조회 테스트',
        status: 'pending',
        dependencies: ['6️⃣ 소유자 Annotation 조회 테스트'],
        indentLevel: 1,
      },
      {
        name: '8️⃣ 권한 없는 사용자 Annotation 조회 시도 (401 에러)',
        status: 'pending',
        dependencies: ['7️⃣ READ_ALL 권한으로 다른 사용자 Annotation 조회 테스트'],
        indentLevel: 1,
      },
      {
        name: '9️⃣ 소유자 Annotation 수정 테스트',
        status: 'pending',
        dependencies: ['8️⃣ 권한 없는 사용자 Annotation 조회 시도 (401 에러)'],
        indentLevel: 1,
      },
      {
        name: '🔟 소유자 Annotation 삭제 테스트',
        status: 'pending',
        dependencies: ['9️⃣ 소유자 Annotation 수정 테스트'],
        indentLevel: 1,
      },
      {
        name: '1️⃣1️⃣ 권한 없는 사용자 Annotation 생성 시도 (401 에러)',
        status: 'pending',
        dependencies: ['🔟 소유자 Annotation 삭제 테스트'],
        indentLevel: 1,
      },
      {
        name: '1️⃣2️⃣ 정리 (테스트 프로젝트 삭제)',
        status: 'pending',
        dependencies: ['1️⃣1️⃣ 권한 없는 사용자 Annotation 생성 시도 (401 에러)'],
        indentLevel: 0,
        cleanup: true,
      },
    ],
  },
  {
    title: '👁️ 권한 기반 Annotation 조회 (READ_ALL)',
    description: 'ADJUDICATOR 역할의 READ_ALL 권한을 통한 모든 사용자 Annotation 조회 테스트 (순차 실행)',
    isSequential: true,
    tests: [
      {
        name: '0️⃣ 사전 정리 (기존 테스트 프로젝트 삭제)',
        status: 'pending',
        isSequential: true,
        indentLevel: 0,
        cleanup: true,
      },
      {
        name: '1️⃣ 테스트용 프로젝트 생성',
        status: 'pending',
        isSequential: true,
        dependencies: ['0️⃣ 사전 정리 (기존 테스트 프로젝트 삭제)'],
        indentLevel: 0,
      },
      {
        name: '2️⃣ 테스트용 사용자 3명 생성 (일반 사용자 2명, ADJUDICATOR 1명)',
        status: 'pending',
        dependencies: ['1️⃣ 테스트용 프로젝트 생성'],
        indentLevel: 1,
      },
      {
        name: '3️⃣ 사용자들을 프로젝트 멤버로 추가',
        status: 'pending',
        dependencies: ['2️⃣ 테스트용 사용자 3명 생성 (일반 사용자 2명, ADJUDICATOR 1명)'],
        indentLevel: 1,
      },
      {
        name: '4️⃣ ADJUDICATOR 역할 할당',
        status: 'pending',
        dependencies: ['3️⃣ 사용자들을 프로젝트 멤버로 추가'],
        indentLevel: 1,
      },
      {
        name: '5️⃣ 일반 사용자1로 Annotation 3개 생성',
        status: 'pending',
        dependencies: ['4️⃣ ADJUDICATOR 역할 할당'],
        indentLevel: 1,
      },
      {
        name: '6️⃣ 일반 사용자2로 Annotation 2개 생성',
        status: 'pending',
        dependencies: ['5️⃣ 일반 사용자1로 Annotation 3개 생성'],
        indentLevel: 1,
      },
      {
        name: '7️⃣ 일반 사용자1 본인 Annotation만 조회 (3개)',
        status: 'pending',
        dependencies: ['6️⃣ 일반 사용자2로 Annotation 2개 생성'],
        indentLevel: 1,
      },
      {
        name: '8️⃣ ADJUDICATOR 모든 Annotation 조회 (5개)',
        status: 'pending',
        dependencies: ['7️⃣ 일반 사용자1 본인 Annotation만 조회 (3개)'],
        indentLevel: 1,
      },
      {
        name: '9️⃣ SOP Instance UID로 조회 (READ_ALL 권한 확인)',
        status: 'pending',
        dependencies: ['8️⃣ ADJUDICATOR 모든 Annotation 조회 (5개)'],
        indentLevel: 1,
      },
      {
        name: '🔟 Series UID로 조회 (READ_ALL 권한 확인)',
        status: 'pending',
        dependencies: ['9️⃣ SOP Instance UID로 조회 (READ_ALL 권한 확인)'],
        indentLevel: 1,
      },
      {
        name: '1️⃣1️⃣ Study UID로 조회 (READ_ALL 권한 확인)',
        status: 'pending',
        dependencies: ['🔟 Series UID로 조회 (READ_ALL 권한 확인)'],
        indentLevel: 1,
      },
      {
        name: '1️⃣2️⃣ Summary API로 전체 통계 조회',
        status: 'pending',
        dependencies: ['1️⃣1️⃣ Study UID로 조회 (READ_ALL 권한 확인)'],
        indentLevel: 1,
      },
      {
        name: '1️⃣3️⃣ 정리 (생성된 Annotation 삭제)',
        status: 'pending',
        dependencies: ['1️⃣2️⃣ Summary API로 전체 통계 조회'],
        indentLevel: 0,
        cleanup: true,
      },
      {
        name: '1️⃣4️⃣ 정리 (생성된 사용자 삭제)',
        status: 'pending',
        dependencies: ['1️⃣3️⃣ 정리 (생성된 Annotation 삭제)'],
        indentLevel: 0,
        cleanup: true,
      },
      {
        name: '1️⃣5️⃣ 정리 (테스트 프로젝트 삭제)',
        status: 'pending',
        dependencies: ['1️⃣4️⃣ 정리 (생성된 사용자 삭제)'],
        indentLevel: 0,
        cleanup: true,
      },
    ],
  },
  {
    title: '🔐 Annotation 권한 조회 API 개선',
    description: 'Annotation 권한 조회 API 개선 기능 테스트 (순차 실행)',
    isSequential: true,
    tests: [
      {
        name: '0️⃣ 사전 정리 (기존 테스트 프로젝트 삭제)',
        status: 'pending',
        isSequential: true,
        indentLevel: 0,
        cleanup: true,
      },
      {
        name: '1️⃣ 테스트용 프로젝트 생성',
        status: 'pending',
        isSequential: true,
        dependencies: ['0️⃣ 사전 정리 (기존 테스트 프로젝트 삭제)'],
        indentLevel: 0,
        delayAfter: 1000,
      },
      {
        name: '2️⃣ 사용자들을 프로젝트 멤버로 추가',
        status: 'pending',
        dependencies: ['1️⃣ 테스트용 프로젝트 생성'],
        indentLevel: 1,
      },
      {
        name: '3️⃣ 테스트용 사용자 조회/확인',
        status: 'pending',
        dependencies: ['2️⃣ 사용자들을 프로젝트 멤버로 추가'],
        indentLevel: 1,
      },
      {
        name: '4️⃣ 본인 권한 조회 (user_id 파라미터 없음, 헤더만)',
        status: 'pending',
        dependencies: ['3️⃣ 테스트용 사용자 조회/확인'],
        indentLevel: 1,
      },
      {
        name: '5️⃣ 본인 권한 조회 (user_id 쿼리 파라미터로 명시)',
        status: 'pending',
        dependencies: ['4️⃣ 본인 권한 조회 (user_id 파라미터 없음, 헤더만)'],
        indentLevel: 1,
      },
      {
        name: '6️⃣ 본인 권한 조회 (쿼리 파라미터와 헤더 모두, 쿼리 우선순위)',
        status: 'pending',
        dependencies: ['5️⃣ 본인 권한 조회 (user_id 쿼리 파라미터로 명시)'],
        indentLevel: 1,
      },
      {
        name: '7️⃣ 다른 사용자 권한 조회 (프로젝트 멤버인 경우)',
        status: 'pending',
        dependencies: ['6️⃣ 본인 권한 조회 (쿼리 파라미터와 헤더 모두, 쿼리 우선순위)'],
        indentLevel: 1,
      },
      {
        name: '8️⃣ project_id 누락 시 400 에러',
        status: 'pending',
        dependencies: ['7️⃣ 다른 사용자 권한 조회 (프로젝트 멤버인 경우)'],
        indentLevel: 1,
      },
      {
        name: '9️⃣ project_id가 0일 때 400 에러',
        status: 'pending',
        dependencies: ['8️⃣ project_id 누락 시 400 에러'],
        indentLevel: 1,
      },
      {
        name: '🔟 project_id가 음수일 때 400 에러',
        status: 'pending',
        dependencies: ['9️⃣ project_id가 0일 때 400 에러'],
        indentLevel: 1,
      },
      {
        name: '1️⃣1️⃣ project_id가 유효하지 않은 형식 (문자열) 400 에러',
        status: 'pending',
        dependencies: ['🔟 project_id가 음수일 때 400 에러'],
        indentLevel: 1,
      },
      {
        name: '1️⃣2️⃣ user_id 없음 (헤더도 쿼리도 없음) 401 에러',
        status: 'pending',
        dependencies: ['1️⃣1️⃣ project_id가 유효하지 않은 형식 (문자열) 400 에러'],
        indentLevel: 1,
      },
      {
        name: '1️⃣3️⃣ 프로젝트 멤버가 아닌 사용자가 다른 사용자 권한 조회 시도 (403 에러)',
        status: 'pending',
        dependencies: ['1️⃣2️⃣ user_id 없음 (헤더도 쿼리도 없음) 401 에러'],
        indentLevel: 1,
      },
      {
        name: '1️⃣4️⃣ 존재하지 않는 프로젝트의 권한 조회 (404/401 에러)',
        status: 'pending',
        dependencies: ['1️⃣3️⃣ 프로젝트 멤버가 아닌 사용자가 다른 사용자 권한 조회 시도 (403 에러)'],
        indentLevel: 1,
      },
      {
        name: '1️⃣5️⃣ target_user_id가 프로젝트 멤버가 아닌 경우 (401 에러)',
        status: 'pending',
        dependencies: ['1️⃣4️⃣ 존재하지 않는 프로젝트의 권한 조회 (404/401 에러)'],
        indentLevel: 1,
      },
      {
        name: '1️⃣6️⃣ 정리 (테스트 프로젝트 삭제)',
        status: 'pending',
        dependencies: ['1️⃣5️⃣ target_user_id가 프로젝트 멤버가 아닌 경우 (401 에러)'],
        indentLevel: 0,
        cleanup: true,
      },
    ],
  },
  {
    title: '🔒 Annotation 보안 강화 (멤버십 + 소유권)',
    description: '프로젝트 멤버십 검증 및 소유권 기반 수정/삭제 제한 테스트 (순차 실행)',
    isSequential: true,
    tests: [
      {
        name: '1️⃣ 프로젝트 멤버가 아닌 사용자 생성 시도 (401 에러)',
        status: 'pending',
        isSequential: true,
        indentLevel: 0,
      },
      {
        name: '2️⃣ 프로젝트 멤버로 Annotation 생성 (쿼리 파라미터)',
        status: 'pending',
        dependencies: ['1️⃣ 프로젝트 멤버가 아닌 사용자 생성 시도 (401 에러)'],
        indentLevel: 0,
      },
      {
        name: '3️⃣ 프로젝트 멤버로 Annotation 생성 (헤더)',
        status: 'pending',
        dependencies: ['2️⃣ 프로젝트 멤버로 Annotation 생성 (쿼리 파라미터)'],
        indentLevel: 0,
      },
      {
        name: '4️⃣ 다른 사용자가 Annotation 수정 시도 (401 에러)',
        status: 'pending',
        dependencies: ['3️⃣ 프로젝트 멤버로 Annotation 생성 (헤더)'],
        indentLevel: 1,
      },
      {
        name: '5️⃣ 본인이 Annotation 수정 (성공)',
        status: 'pending',
        dependencies: ['4️⃣ 다른 사용자가 Annotation 수정 시도 (401 에러)'],
        indentLevel: 1,
      },
      {
        name: '6️⃣ 다른 사용자가 Annotation 삭제 시도 (401 에러)',
        status: 'pending',
        dependencies: ['5️⃣ 본인이 Annotation 수정 (성공)'],
        indentLevel: 1,
      },
      {
        name: '7️⃣ 본인이 Annotation 삭제 (성공)',
        status: 'pending',
        dependencies: ['6️⃣ 다른 사용자가 Annotation 삭제 시도 (401 에러)'],
        indentLevel: 1,
      },
    ],
  },
];

