import { TestSection } from './types';

export const getDicomSections = (): TestSection[] => [
  {
    title: '🔍 DICOM 전체 조회 + 할당 여부 확인',
    description: 'project_id 옵셔널화, READ_ALL 권한, check_assignment_for_project 테스트',
    isSequential: false,
    tests: [
      {
        name: 'DICOM Studies 전체 조회 (project_id 없음)',
        status: 'pending',
        indentLevel: 0,
      },
      {
        name: 'DICOM Studies 프로젝트별 조회 (project_id 있음)',
        status: 'pending',
        indentLevel: 0,
      },
      {
        name: 'DICOM Series 전체 조회 (project_id 없음)',
        status: 'pending',
        indentLevel: 0,
      },
      {
        name: 'DICOM Instances 전체 조회 (project_id 없음)',
        status: 'pending',
        indentLevel: 0,
      },
      {
        name: '할당 여부 확인 (check_assignment_for_project)',
        status: 'pending',
        indentLevel: 0,
      },
      {
        name: '전체 조회 + 할당 여부 확인 (통합)',
        status: 'pending',
        indentLevel: 0,
      },
      {
        name: '프로젝트별 조회 + 할당 여부 확인',
        status: 'pending',
        indentLevel: 0,
      },
      {
        name: '다른 프로젝트 할당 여부 확인',
        status: 'pending',
        indentLevel: 0,
      },
      {
        name: '잘못된 project_id (0) 에러 처리',
        status: 'pending',
        indentLevel: 0,
      },
      {
        name: '잘못된 project_id (음수) 에러 처리',
        status: 'pending',
        indentLevel: 0,
      },
    ],
  },
  {
    title: '👤 DICOM Patient API (QIDO-RS 프록시)',
    description: 'Patient 레벨 QIDO-RS 프록시 + RBAC 필터링 + 페이지네이션 테스트 (순차 실행)',
    isSequential: true,
    tests: [
      {
        name: '🔧 Setup: 테스트용 프로젝트 생성',
        status: 'pending',
        isSequential: true,
        indentLevel: 0,
        delayAfter: 1500,
      },
      {
        name: '🔧 Setup: Study 할당 (Patient 데이터 생성)',
        status: 'pending',
        dependencies: ['🔧 Setup: 테스트용 프로젝트 생성'],
        isSequential: true,
        indentLevel: 1,
        delayAfter: 1000,
      },
      {
        name: 'Patient 전체 조회 (project_id 있음)',
        status: 'pending',
        dependencies: ['🔧 Setup: Study 할당 (Patient 데이터 생성)'],
        indentLevel: 1,
      },
      {
        name: 'Patient 페이지네이션 (limit=1)',
        status: 'pending',
        dependencies: ['Patient 전체 조회 (project_id 있음)'],
        indentLevel: 1,
      },
      {
        name: 'Patient 필터링 (PatientName)',
        status: 'pending',
        dependencies: ['Patient 페이지네이션 (limit=1)'],
        indentLevel: 1,
      },
      {
        name: 'Patient 필터링 (PatientID)',
        status: 'pending',
        dependencies: ['Patient 필터링 (PatientName)'],
        indentLevel: 1,
      },
      {
        name: 'Patient DICOM JSON 구조 검증',
        status: 'pending',
        dependencies: ['Patient 필터링 (PatientID)'],
        indentLevel: 1,
      },
      {
        name: 'project_id 없이 조회 (400 에러)',
        status: 'pending',
        dependencies: ['Patient DICOM JSON 구조 검증'],
        indentLevel: 1,
      },
      {
        name: '잘못된 project_id (0) 에러 처리',
        status: 'pending',
        dependencies: ['project_id 없이 조회 (400 에러)'],
        indentLevel: 1,
      },
      {
        name: '잘못된 project_id (음수) 에러 처리',
        status: 'pending',
        dependencies: ['잘못된 project_id (0) 에러 처리'],
        indentLevel: 1,
      },
      {
        name: '🧹 Cleanup: 테스트 프로젝트 삭제',
        status: 'pending',
        dependencies: ['잘못된 project_id (음수) 에러 처리'],
        cleanup: true,
        isSequential: true,
        indentLevel: 1,
      },
    ],
  },
  {
    title: '📊 DICOM Series API (QIDO-RS 프록시)',
    description: 'Series 레벨 QIDO-RS 프록시 + RBAC 필터링 + 페이지네이션 + 썸네일 URL 테스트 (실제 PACS 데이터 사용)',
    isSequential: true,
    tests: [
      {
        name: '🔐 Login: Keycloak 로그인 (Bearer 토큰 획득)',
        status: 'pending',
        isSequential: true,
        indentLevel: 0,
      },
      {
        name: '🔧 Setup: 실제 PACS 데이터 확인 (project_id=2)',
        status: 'pending',
        dependencies: ['🔐 Login: Keycloak 로그인 (Bearer 토큰 획득)'],
        isSequential: true,
        indentLevel: 0,
      },
      {
        name: 'Series 전체 조회 (SarcopeniaCase1)',
        status: 'pending',
        dependencies: ['🔧 Setup: 실제 PACS 데이터 확인 (project_id=2)'],
        indentLevel: 1,
      },
      {
        name: 'Series 개수 검증 (1개 예상)',
        status: 'pending',
        dependencies: ['Series 전체 조회 (SarcopeniaCase1)'],
        indentLevel: 1,
      },
      {
        name: 'Series 페이지네이션 (limit=1)',
        status: 'pending',
        dependencies: ['Series 개수 검증 (1개 예상)'],
        indentLevel: 1,
      },
      {
        name: 'Series 필터링 (Modality=CT)',
        status: 'pending',
        dependencies: ['Series 페이지네이션 (limit=1)'],
        indentLevel: 1,
      },
      {
        name: 'Series 필터링 (Modality=SM)',
        status: 'pending',
        dependencies: ['Series 필터링 (Modality=CT)'],
        indentLevel: 1,
      },
      {
        name: 'Series DICOM JSON 구조 검증',
        status: 'pending',
        dependencies: ['Series 필터링 (Modality=SM)'],
        indentLevel: 1,
      },
      {
        name: 'Series thumbnail_url 필드 검증',
        status: 'pending',
        dependencies: ['Series DICOM JSON 구조 검증'],
        indentLevel: 1,
      },
      {
        name: 'thumbnail_url 형식 검증 (WADO-RS 표준)',
        status: 'pending',
        dependencies: ['Series thumbnail_url 필드 검증'],
        indentLevel: 1,
      },
      {
        name: '🔐 Login: 일반 USER 로그인 (test_user)',
        status: 'pending',
        dependencies: ['thumbnail_url 형식 검증 (WADO-RS 표준)'],
        indentLevel: 1,
      },
      {
        name: 'SUPER_ADMIN: project_id 없이 조회 (성공 - 전체 접근 권한)',
        status: 'pending',
        dependencies: ['🔐 Login: 일반 USER 로그인 (test_user)'],
        indentLevel: 1,
      },
      {
        name: '일반 USER: project_id 없이 조회 (400 에러)',
        status: 'pending',
        dependencies: ['SUPER_ADMIN: project_id 없이 조회 (성공 - 전체 접근 권한)'],
        indentLevel: 1,
      },
      {
        name: '일반 USER: project_id와 함께 조회 (성공)',
        status: 'pending',
        dependencies: ['일반 USER: project_id 없이 조회 (400 에러)'],
        indentLevel: 1,
      },
      {
        name: '잘못된 project_id (0) 에러 처리',
        status: 'pending',
        dependencies: ['일반 USER: project_id와 함께 조회 (성공)'],
        indentLevel: 1,
      },
      {
        name: '잘못된 project_id (음수) 에러 처리',
        status: 'pending',
        dependencies: ['잘못된 project_id (0) 에러 처리'],
        indentLevel: 1,
      },
      {
        name: '존재하지 않는 PatientID 조회 (빈 배열)',
        status: 'pending',
        dependencies: ['잘못된 project_id (음수) 에러 처리'],
        indentLevel: 1,
      },
      {
        name: '존재하지 않는 Modality 조회 (빈 배열)',
        status: 'pending',
        dependencies: ['존재하지 않는 PatientID 조회 (빈 배열)'],
        indentLevel: 1,
      },
      {
        name: '다른 프로젝트로 조회 (빈 배열 - RBAC)',
        status: 'pending',
        dependencies: ['존재하지 않는 Modality 조회 (빈 배열)'],
        indentLevel: 1,
      },
      {
        name: '🧹 Cleanup: 실제 데이터 사용 - 삭제 불필요',
        status: 'pending',
        dependencies: ['다른 프로젝트로 조회 (빈 배열 - RBAC)'],
        cleanup: true,
        isSequential: true,
        indentLevel: 1,
      },
    ],
  },
];

