# Default configuration
# These values can be overridden by:
# 1. config/{environment}.toml
# 2. .env file
# 3. Environment variables with APP_ prefix (highest priority)

[server]
host = "0.0.0.0"
port = 8080
workers = 4

[database]
host = "localhost"
port = 5432
username = "admin"
password = "admin123"
database = "pacs_db"
max_connections = 10
min_connections = 2

[keycloak]
url = "http://localhost:8080"
realm = "pacs"
client_id = "pacs-server"
client_secret = ""

[logging]
level = "info"
format = "json"

[jwt]
secret = "your-secret-key-change-this-in-production"
expiration_hours = 24

[cors]
enabled = false
allowed_origins = ["http://localhost:3000", "http://localhost:8080"]
allowed_methods = ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
allowed_headers = ["Content-Type", "Authorization", "X-Requested-With"]
expose_headers = ["Content-Length", "X-Total-Count"]
max_age = 3600

[object_storage]
# All object storage settings should be configured via environment variables:
# APP_OBJECT_STORAGE__PROVIDER
# APP_OBJECT_STORAGE__BUCKET_NAME
# APP_OBJECT_STORAGE__REGION
# APP_OBJECT_STORAGE__ENDPOINT (optional)
# APP_OBJECT_STORAGE__ACCESS_KEY_ID
# APP_OBJECT_STORAGE__SECRET_ACCESS_KEY


[signed_url]
default_ttl = 600  # 10 minutes
max_ttl = 3600     # 1 hour
