# Development environment configuration

[server]
host = "0.0.0.0"
port = 8080
workers = 2

[database]
host = "localhost"
port = 5432
username = "admin"
password = "admin123"
database = "pacs_db"
max_connections = 5
min_connections = 1

[keycloak]
url = "http://localhost:8080"
realm = "pacs-dev"
client_id = "pacs-server-dev"
client_secret = "dev-secret"

[logging]
level = "debug"
format = "pretty"

[object_storage]
# All object storage settings should be configured via environment variables:
# APP_OBJECT_STORAGE__PROVIDER
# APP_OBJECT_STORAGE__BUCKET_NAME
# APP_OBJECT_STORAGE__REGION
# APP_OBJECT_STORAGE__ENDPOINT (optional)
# APP_OBJECT_STORAGE__ACCESS_KEY_ID
# APP_OBJECT_STORAGE__SECRET_ACCESS_KEY

[signed_url]
default_ttl = 600   # 10 minutes
max_ttl = 3600      # 1 hour

[dcm4chee]
base_url = "http://localhost:8080"
qido_path = "/dcm4chee-arc/aets/DCM4CHEE/rs"
wado_path = "/dcm4chee-arc/aets/DCM4CHEE/wado"
aet = "DCM4CHEE"
timeout_ms = 5000

[dcm4chee.db]
host = "localhost"
port = 5457
database = "postgres"
username = "pacsadmin"
password = "HhL}qb(tl}?zJ4}("