# Development environment configuration

[server]
host = "127.0.0.1"
port = 8080
workers = 2

[database]
host = "localhost"
port = 5432
username = "admin"
password = "admin123"
database = "pacs_db"
max_connections = 5
min_connections = 1

[keycloak]
url = "http://localhost:8080"
realm = "pacs-dev"
client_id = "pacs-server-dev"
client_secret = "dev-secret"

[logging]
level = "debug"
format = "pretty"

[object_storage]
provider = "s3"  # Use S3 for development
bucket_name = "pacs-masks"
region = "ap-northeast-2"
endpoint = ""  # AWS S3 endpoint (leave empty for default)
access_key_id = ""  # Will be overridden by .env
secret_access_key = ""  # Will be overridden by .env

[signed_url]
default_ttl = 600   # 10 minutes
max_ttl = 3600      # 1 hour
